### ISSUE TITLE
file_url removed in newest API changes.

### ISSUE THREAD

**Issue by Codingale** [FPtje/gmosh#20]
Needs to use methdod: 
https://gmod.facepunch.com/f/gmoddev/oveg/Valve-removed-field-for-Steamworks-API-call-GetPublishedFileDetails/1/

https://api.steampowered.com/IPublishedFileService/GetDetails/v1/?key=<steamapikey>&publishedfileids[0]=<workshopid>

Currently downloading is broken in  Gmosh/GmoshUI

**Comment by FPtje** [comment]
Bollocks

**Comment by FPtje** [comment]
I just looked at it. The problem with it is that it seems to require an API key. Gmosh currently doesn't have one because until now it could do everything with that URL and `gmpublish`. I don't want to have to ask people to get an API key to be able to download shit from the workshop.

And in all honesty I don't have much reason to maintain this either. For now it's best to mark this as won't fix.

**Comment by Codingale** [comment]
Oh side note, I've used an online service to download them however they (and sometimes Gmosh) would download the addon and I'd need to extract it then open the `.gma` in GmoshUI to extract it is there a way you can detect if it's nested like this?

**Comment by FPtje** [comment]
I'm not sure
